[package]
name = "werdle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getch = "0.3.1"
rand = "0.8.5"
enable-ansi-support = "0.1.2"